
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const CreateQuestion = lazy(() => import("./pages/CreateQuestion.tsx"));
const Leaderboard = lazy(() => import("./pages/Leaderboard.tsx"));
const QuizBattle = lazy(() => import("./pages/QuizBattle.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/create-question", element: <UserGuard><CreateQuestion /></UserGuard>},
	{ path: "/createquestion", element: <UserGuard><CreateQuestion /></UserGuard>},
	{ path: "/leaderboard", element: <UserGuard><Leaderboard /></UserGuard>},
	{ path: "/quiz-battle", element: <UserGuard><QuizBattle /></UserGuard>},
	{ path: "/quizbattle", element: <UserGuard><QuizBattle /></UserGuard>},

];
